import Foundation

struct SleepSession: Codable, Identifiable {
    var id: Int? // Optional because we might not need it or it might be generated by backend
    var sleepDate: String
    var bedtime: String
    var wakeTime: String
    var durationMin: Int
    
    enum CodingKeys: String, CodingKey {
        case id
        case sleepDate = "sleep_date"
        case bedtime
        case wakeTime = "wake_time"
        case durationMin = "duration_min"
    }
}

struct SleepSessionRequest: Codable {
    var sleepDate: String
    var bedtime: String
    var wakeTime: String
    var durationMin: Int
    
    enum CodingKeys: String, CodingKey {
        case sleepDate = "sleep_date"
        case bedtime
        case wakeTime = "wake_time"
        case durationMin = "duration_min"
    }
}
